[global]
    update every = 1

[ml]
    enabled = no

[registry]
    enabled = no

[plugins]
    proc = yes
    diskspace = yes
    cgroups = no
    apps = no
    ebpf = no
    go.d = no
    python.d = no
    charts.d = no
    tc = no
    nfacct = no
    perf = no
    slabinfo = no
    timex = no
    idlejitter = no
